#!/usr/bin/env bash
# =============================================================================
# HireLens — Full Deploy Script
# Runs from your LOCAL machine. Deploys everything to EC2 from scratch.
#
# First-time setup:
#   bash aws/deploy.sh --bootstrap
#
# Update app after a code change:
#   bash aws/deploy.sh
#
# Required env vars (or pass as args):
#   EC2_HOST      — public IP or DNS of your EC2 instance
#   SSH_KEY       — path to your .pem key file
#   GHCR_USER     — your GitHub username (for ghcr.io image pull)
#   GHCR_TOKEN    — GitHub personal access token (repo + write:packages scope)
#   POSTGRES_PASSWORD — strong random password
#
# Example:
#   EC2_HOST=54.1.2.3 SSH_KEY=~/.ssh/hirelens.pem \
#   GHCR_USER=akshat GHCR_TOKEN=ghp_xxx \
#   POSTGRES_PASSWORD=s3cr3t bash aws/deploy.sh
# =============================================================================
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
EC2_HOST="${EC2_HOST:?Set EC2_HOST to your EC2 IP/DNS}"
SSH_KEY="${SSH_KEY:?Set SSH_KEY to path of your .pem file}"
GHCR_USER="${GHCR_USER:?Set GHCR_USER to your GitHub username}"
GHCR_TOKEN="${GHCR_TOKEN:?Set GHCR_TOKEN to a GitHub PAT}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD}"
APP_DIR="/opt/hirelens"
SSH="ssh -i ${SSH_KEY} -o StrictHostKeyChecking=no ubuntu@${EC2_HOST}"
SCP="scp -i ${SSH_KEY} -o StrictHostKeyChecking=no"
BOOTSTRAP="${1:-}"

echo "========================================"
echo "  HireLens Deploy → ${EC2_HOST}"
echo "========================================"

# ── Step 1: Bootstrap (first time only) ──────────────────────────────────────
if [ "${BOOTSTRAP}" = "--bootstrap" ]; then
    echo "[1/5] Bootstrapping EC2 instance..."
    $SCP aws/setup-ec2.sh "ubuntu@${EC2_HOST}:~/setup-ec2.sh"
    $SSH "bash ~/setup-ec2.sh"
else
    echo "[1/5] Skipping bootstrap (use --bootstrap for first-time setup)"
fi

# ── Step 2: Upload S3 buckets (first time) ───────────────────────────────────
if [ "${BOOTSTRAP}" = "--bootstrap" ]; then
    echo "[2/5] Setting up S3 buckets..."
    bash aws/s3-setup.sh
    echo "  Syncing model artifacts to S3..."
    ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    aws s3 sync models/fine_tuned/hirelens_matcher \
        "s3://hirelens-models-${ACCOUNT_ID}/models/hirelens_matcher/" \
        --exclude "*.pyc" --exclude "__pycache__/*"
    echo "  Model uploaded to S3."
else
    echo "[2/5] Skipping S3 setup"
fi

# ── Step 3: Copy production files ─────────────────────────────────────────────
echo "[3/5] Copying production files to ${EC2_HOST}..."
$SSH "mkdir -p ${APP_DIR}"

$SCP docker-compose.prod.yml "ubuntu@${EC2_HOST}:${APP_DIR}/docker-compose.prod.yml"
$SCP aws/cloudwatch-agent.json "ubuntu@${EC2_HOST}:~/cloudwatch-agent.json"

# Generate .env.prod from current .env + production overrides
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
cat > /tmp/hirelens-env-prod <<EOF
# Generated by aws/deploy.sh — do not edit manually
APP_ENV=production
APP_DEBUG=false
API_WORKERS=1
API_RELOAD=false
LOG_LEVEL=INFO

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=hirelens
POSTGRES_USER=hirelens_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql+asyncpg://hirelens_user:${POSTGRES_PASSWORD}@postgres:5432/hirelens

REDIS_URL=redis://redis:6379/0

MLFLOW_TRACKING_URI=http://mlflow:5000
MLFLOW_EXPERIMENT_NAME=hirelens-resume-matching

AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
AWS_S3_RESUMES_BUCKET=hirelens-resumes-${ACCOUNT_ID}
AWS_S3_MODELS_BUCKET=hirelens-models-${ACCOUNT_ID}

MODEL_CACHE_DIR=/app/models/cache
FINE_TUNED_MODEL_PATH=/app/models/fine_tuned/hirelens_matcher
SPACY_MODEL=en_core_web_sm

CORS_ORIGINS=http://${EC2_HOST},https://${EC2_HOST}

APP_SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET_KEY=$(openssl rand -hex 32)

GHCR_USER=${GHCR_USER}
EOF
$SCP /tmp/hirelens-env-prod "ubuntu@${EC2_HOST}:${APP_DIR}/.env.prod"
rm /tmp/hirelens-env-prod

# ── Step 4: Pull images + start services ─────────────────────────────────────
echo "[4/5] Pulling Docker images and starting services..."
$SSH "
    set -e
    # Login to ghcr.io
    echo '${GHCR_TOKEN}' | docker login ghcr.io -u '${GHCR_USER}' --password-stdin

    # Pull latest images
    cd ${APP_DIR}
    docker compose -f docker-compose.prod.yml pull

    # Start (or restart changed) services
    docker compose -f docker-compose.prod.yml up -d

    # Configure CloudWatch agent
    sudo amazon-cloudwatch-agent-ctl \
        -a fetch-config -m ec2 -s \
        -c file:/home/ubuntu/cloudwatch-agent.json

    # Show running containers
    docker compose -f docker-compose.prod.yml ps
"

# ── Step 5: Smoke test ────────────────────────────────────────────────────────
echo "[5/5] Smoke testing..."
sleep 20  # give containers time to start

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://${EC2_HOST}/health")
if [ "${HTTP_CODE}" = "200" ]; then
    echo "  Health check: HTTP ${HTTP_CODE} ✓"
    curl -s "http://${EC2_HOST}/health" | python3 -m json.tool
else
    echo "  Health check: HTTP ${HTTP_CODE} ✗"
    echo "  Run: ssh -i ${SSH_KEY} ubuntu@${EC2_HOST} 'docker compose -f ${APP_DIR}/docker-compose.prod.yml logs backend'"
    exit 1
fi

echo ""
echo "========================================"
echo "  Deploy COMPLETE"
echo "  App running at: http://${EC2_HOST}"
echo "========================================"
